# Generated by Django 3.2.6 on 2021-08-15 00:07

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
