# Generated by Django 3.2.6 on 2021-08-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
    ]
