# Generated by Django 3.2.6 on 2021-08-17 15:47

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
